registration:
  role: customer
  bankCode: SECTBNK
  accountNumberLength: 5
message:
  success: success
  failure: failure
role:
  customer: customer
  merchant: merchant
springdoc:
  api-docs:
    path: /apiDocs
transaction:
  deposit: D
  withdraw: W
  success: success
