server:
  port: ${PORT:0}
  servlet:
    context-path: /securebnk/transactions
spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/secure-trust-bank?allowPublicKeyRetrieval=true&&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
      auto-offset-reset: earliest
      group-id: authentication
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.securetrustbank.transactions.customserde.CustomDeserializer

  cloud:
    consul:
      discovery:
        instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckPath: /securebnk/transactions/actuator/health
